### ISSUE TITLE
ansi2html.sh bugs completely if locale is not utf8

### ISSUE THREAD

**Issue by denilsonsa** [pixelb/scripts#18]
See ~~the attached files~~ [the files in this Gist](https://gist.github.com/denilsonsa/caede7919c7d4b2ad2b5) (because GitHub does not allow attachments to issues).

    LC_ALL=en_US.UTF-8 ./ansi2html.sh < bug.txt > worksfine.html
    LC_ALL=C ./ansi2html.sh < bug.txt > buggy.html

Reproduced on Linux Ubuntu 13 and 14.

**Comment by pixelb** [comment]
Yes this is a regression introduced by the awk character by character processing, rather than the previous scheme of matching characters, which degenerated to an equivalent matching of a set of bytes in unibyte locales.
