### ISSUE TITLE
How to force wrapping of lines in ansi2html.sh output?

### ISSUE THREAD

**Issue by katrinleinweber** [pixelb/scripts#20]
Thank you so much for [ansi2html.sh](https://github.com/pixelb/scripts/commits/master/scripts/ansi2html.sh) :-)   I'm using it to [provide summaries](https://github.com/katrinleinweber/PhD-thesis#helper-tools) of git-tracked changes to document reviewers who don't use git themselves.

For that purpose, I'd like to learn how the script could insert line-breaks after a certain number of characters. Thanks for any hints!

**Comment by harvimt** [comment]
You can use a tool like `fold` `wrap` or `fmt` see: http://unix.stackexchange.com/questions/25173/how-can-i-wrap-text-at-a-certain-column-size for details.

`fold` looks to be the easiest to use, then you could do `cat foo.txt | fold -w -s $COLWIDTH | ansi2html.sh`
