### ISSUE TITLE
Colours Not Correct

### ISSUE THREAD

**Issue by AncientRepositoryOfKnowledge** [pixelb/scripts#23]
Sorry if there's a solution to this, but it seems that the colours in the HTML don't match the colours from the terminal?

**Comment by harvimt** [comment]
I think this is expected. ansi2html just converts the ansi color codes, it doesn't know what your terminals defaults are. So if the ansi escape code says "black background, default foreground", that's what you get in the HTML, but HTML always defaults to white background, black foreground so this is what you get.

I haven't used this script in a while, but I think there's a flag to pass, to tell it what your terminal default foreground and background are so it comes out right in the html.

**Comment by pixelb** [comment]
@harvimt is correct. You probably want the --bg=dark option
